src/Academic/urls.py
from django.conf.urls import url
from . import views
from cv_portfolio.views import PreviewCV,PortfolioView

app_name="Academic"

urlpatterns = [
    url(r'^$', views.DepartmentView,name="dept_list"),
    url(r'^(?P<dept_name_short>[-\w]+)/list/$', views.DepartmentDetail,name="dept_detail"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/$', views.StudentList,name="profile_list"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/$', views.StudentDetail,name="detail"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/edit/$', views.ProfileUpdate,name="update"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/cv/$',PreviewCV,name="cv"),
    # url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/portfolio/$',PortfolioView,name="portfolio"),
    url(r'^profile/create/$', views.ProfileCreate,name="create"),


]

src/Campus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^$',views.Home,name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^department/',include("Academic.urls")),
    url(r'^students/',include("Users.urls")),
    url(r'^',include("cv_portfolio.urls")),
    url(r'^',include("Notifications.urls")),
    url(r'^', include('django.contrib.auth.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/Users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name="Users"

urlpatterns = [

    url(r'^register/$',views.Register,name="register"),
    url(r'^login/$',views.UserLogin,name="login"),
    url(r'^logout/$',views.User_Logout,name="logout"),
    url(r'^profile/$',views.ProfileView,name="profile"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',views.ActivateProfile,name="activate"),

    # Password Reset

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views. password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # Password Change

    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),

]

src/cv_portfolio/urls.py
from django.conf.urls import url
from . import views

app_name="cv_portfolio"

urlpatterns = [

    # Create Informations

    url(r'^aditionalinfo/create/$', views.CreateAdditionalInfo,name="create_aditionalinfo"),
    url(r'^resume/upload/$', views.UploadResume,name="upload_resume"),
    url(r'^portfolio/create/$', views.PortfolioView,name="create_portfolio"),
    url(r'^skills/create/$', views.CreateTechnicalSkill,name="create_skill"),
    url(r'^education/create/$', views.CreateEducationalInfo,name="create_edu"),
    url(r'^work/create/$', views.CreateWorkHistory,name="create_work"),
    url(r'^service/create/$', views.ServiceCreationView,name="service"),
    url(r'^success/create/$', views.CreationSuccessInfo,name="success"),
    url(r'^working_process/create/$', views.CreationWorkingProcess,name="working_process"),
    url(r'^clients/create/$', views.CreateClients,name="create_clients"),

    # List and Detail

    url(r'^skills/list/$', views.SkillList,name="skill_list"),
    url(r'^(?P<user>[-\w]+)/skills/(?P<pk>[-\d]+)/detail/$', views.Skilldetail,name="skill_detail"),

    url(r'^portfolio/list/$', views.PortfolioList,name="portfolio_list"),
    url(r'^portfolio/(?P<pk>[-\d]+)/detail/$', views.PortfolioDetail,name="portfolio_detail"),
    url(r'^(?P<user>[-\w]+)/portfolio/(?P<pk>[-\d]+)/detail/$', views.PortfolioDetailforUser,name="portfolio_detail_user"),

    url(r'^education/list/$', views.EducationalInfoList,name="edu_list"),
    url(r'^(?P<user>[-\w]+)/education/(?P<pk>[-\d]+)/detail/$', views.EducationalInfoDetail,name="edu_detail"),

    url(r'^work/list/$', views.WorkHistoryList,name="work_list"),
    url(r'^(?P<user>[-\w]+)/work/(?P<pk>[-\d]+)/detail/$', views.DetailHistoryList,name="work_detail"),

    url(r'^service/list/$', views.ServiceInfoList,name="service_list"),
    url(r'^(?P<user>[-\w]+)/service/(?P<pk>[-\d]+)/detail/$', views.ServiceInfoDetail,name="service_detail"),

    url(r'^working_process/list/$', views.WorkingProcessList,name="working_process_list"),
    url(r'^(?P<user>[-\w]+)/working_process/(?P<pk>[-\d]+)/detail/$', views.WorkingProcessDetail,name="working_process_detail"),

    url(r'^clients/list/$', views.ClientList,name="clients_list"),
    url(r'^(?P<user>[-\w]+)/clients/(?P<pk>[-\d]+)/detail/$', views.ClientDetail,name="clients_detail"),




    # Update Informations

    url(r'^aditionalinfo/edit/$', views.UpdateAdditionalInfo,name="update_aditionalinfo"),
    url(r'^resume/edit/$', views.UpdateResume,name="update_resume"),
    url(r'^success/edit/$', views.UpdateSuccessInfo,name="update_success"),
    url(r'^(?P<user>[-\w]+)/skills/(?P<pk>[-\d]+)/edit/$', views.UpdateTechnicalSkill,name="update_skill"),
    url(r'^(?P<user>[-\w]+)/education/(?P<pk>[-\d]+)/edit/$', views.UpdateEducationalInfo,name="update_edu"),
    url(r'^(?P<user>[-\w]+)/portfolio/(?P<pk>[-\d]+)/edit/$', views.UpdatePortfolio,name="update_portfolio"),
    url(r'^(?P<user>[-\w]+)/work/(?P<pk>[-\d]+)/edit/$', views.UpdateWorkHistory,name="update_work"),
    url(r'^(?P<user>[-\w]+)/service/(?P<pk>[-\d]+)/edit/$', views.UpdateServiceInfo,name="update_service_info"),
    url(r'^(?P<user>[-\w]+)/working_process/(?P<pk>[-\d]+)/edit/$', views.UpdateWorkingProcess,name="update_working_process"),
    url(r'^(?P<user>[-\w]+)/clients/(?P<pk>[-\d]+)/edit/$', views.UpdateClients,name="update_clients"),


    # Delete Informations

    url(r'^(?P<user>[-\w]+)/skills/(?P<pk>[-\d]+)/delete/$', views.DeleteTechnicalSkill,name="delete_skill"),
    url(r'^(?P<user>[-\w]+)/education/(?P<pk>[-\d]+)/delete/$', views.DeleteEducationalInfo,name="delete_edu"),
    url(r'^(?P<user>[-\w]+)/portfolio/(?P<pk>[-\d]+)/delete/$', views.DeletePortfolio,name="delete_portfolio"),
    url(r'^(?P<user>[-\w]+)/work/(?P<pk>[-\d]+)/delete/$', views.DeleteWorkHistory,name="delete_work"),
    url(r'^(?P<user>[-\w]+)/service/(?P<pk>[-\d]+)/delete/$', views.DeleteService,name="delete_service"),
    url(r'^(?P<user>[-\w]+)/working_process/(?P<pk>[-\d]+)/delete/$', views.DeleteWorkingProcess,name="delete_working_process"),
    url(r'^(?P<user>[-\w]+)/clients/(?P<pk>[-\d]+)/delete/$', views.DeleteClients,name="delete_clients"),



]

src/Academic/models.py
import datetime
from django.db import models
from .utils import year_dropdown






class Department(models.Model):

    dept_name       =models.CharField(max_length=250,primary_key=True,unique=True)
    dept_name_short =models.CharField(max_length=250,unique=True)


    class Meta:

        ordering=["dept_name"]
        verbose_name="Department"
        verbose_name_plural="Departments"

    def __str__(self):

        return str(self.dept_name_short)

src/Academic/views.py
from django.shortcuts import render
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponseRedirect,HttpResponse
from .models import Department
from Users.models import Profile
from Users.forms import ProfileUpdateForm,ProfileCreateForm
from cv_portfolio.models import(TechnicalSkills,
                                Education,
                                WorkHistory,
                                Portfolio,
                                AdditionalInfo,
                                Clients,
                                Service,
                                Succeess,
                                WorkingProcess)




def DepartmentView(request):

    dept_list_qs=Department.objects.all()

    template_name="Academic/department_list.html"
    context={

        "dept_list_qs":dept_list_qs,

    }

    return render(request,template_name,context)


def DepartmentDetail(request,dept_name_short=None):

    dept_name=Department.objects.filter(dept_name_short=dept_name_short)
    qs=Profile.objects.filter(dept_name=dept_name)

    template_name="Academic/department_detail.html"
    context={

        "qs":qs,
    }

    return render(request,template_name,context)


def StudentList(request,dept_name=None,dept_session=None):

    dept_name   =Department.objects.get(dept_name_short=dept_name)

    if dept_name:

        qs=Profile.objects.filter(dept_name=dept_name,academic_year=dept_session)

        paginator = Paginator(qs, 25) # Show 25 student_list per page

        page = request.GET.get('page')
        try:
            student_list = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            student_list = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            student_list = paginator.page(paginator.num_pages)

    template_name="Academic/profile_list.html"

    context={
            "qs":qs,
            "dept_name":dept_name,
            "student_list":student_list
    }

    return render(request,template_name,context)


def StudentDetail(request,dept_name=None,dept_session=None,reg_number=None):

    try:

        dept_name   =Department.objects.get(dept_name_short=dept_name)

        if dept_name:

            qs=Profile.objects.get(dept_name=dept_name,academic_year=dept_session,reg_number=reg_number)
            add_info=AdditionalInfo.objects.filter(user=qs.user)
            skill_=TechnicalSkills.objects.filter(user=qs.user)
            education=Education.objects.filter(user=qs.user)
            work=WorkHistory.objects.filter(user=qs.user)
            port_folio=Portfolio.objects.filter(user=qs.user)
            clients=Clients.objects.filter(user=qs.user)
            service=Service.objects.filter(user=qs.user)
            success=Succeess.objects.filter(user=qs.user)
            work_process=WorkingProcess.objects.filter(user=qs.user)
            x=work_process.count() // 2

        template_name="Academic/profile_detail.html"
        context={
                    "qs":qs,
                    "dept_name":dept_name,
                    "skill_":skill_,
                    "education":education,
                    "work":work,
                    "port_folio":port_folio,
                    "add_info":add_info,
                    "clients":clients,
                    "service":service,
                    "success":success,
                    "work_process1":work_process[:x],
                    "work_process2":work_process[x:]

                }

        return render(request,template_name,context)

    except:

        return render(request,"Academic/profile404.html",{})


def ProfileUpdate(request,dept_name=None,dept_session=None,reg_number=None):

    dept_name   =Department.objects.get(dept_name_short=dept_name)

    if dept_name:

        instance=Profile.objects.get(dept_name=dept_name,academic_year=dept_session,reg_number=reg_number)

    form =ProfileUpdateForm(request.POST or None,instance=instance)

    if form.is_valid():

        instance=form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully Updated Your Informations")
        return HttpResponseRedirect("/students/profile")

    template_name="Academic/profile_update.html"
    context={"instance":instance,"form":form}

    return render(request,template_name,context)


def ProfileCreate(request):

    user_exists=Profile.objects.filter(user=request.user).exists()
    form=ProfileCreateForm(request.POST or None)
    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        if not user_exists:
            instance.save()
            messages.success(request, "Successfully Created Your Profile")
            return HttpResponseRedirect("/students/profile")
        else:
            return HttpResponse("Profile Already Exists")

    template_name="Academic/profile_create.html"
    context={
        "form":form
    }

    return render(request,template_name,context)

src/templates/Academic/department_detail.html
{% extends "Home/base.html" %}
{% load static %}
{% block content %}

<div class="block">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-offset-3">
                <section class="news-small" id="news-small">
                    <header>
                        <h1>Batch List</h>
                    </header>
                    <div class="section-content">
                        {% if qs.count == 0 %}
                        <font face="verdana" color="red" size="4">
                            No Batch Found !!!
                        </font>
                        {% else %}
                        <font face="verdana" color="blue" size="4">
                            Total {{ qs.count }} Batch Found.
                        </font>
                        {% endif %}
                        <br>

                        <table class="table">

                            <tbody>
                                {% for ob in qs %}
                                {% if forloop.counter|divisibleby:2 %}
                                    <tr class="active">
                                        <td>
                                            <font face="verdana" color="green"  size="5">
                                                <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                                                <a href="{% url "Academic:profile_list" ob.dept_name ob.academic_year  %}">{{ ob.academic_year }}</a>
                                            </font>
                                        </td>
                                    </tr>
                                {% else %}
                                <tr class="warning">
                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                                            <a href="{% url "Academic:profile_list" ob.dept_name ob.academic_year  %}">{{ ob.academic_year }}</a>
                                        </font>
                                    </td>
                                </tr>
                                {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

src/templates/Academic/department_list.html
{% extends "Home/base.html" %}
{% load static %}
{% block content %}

<div class="block">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-offset-3">
                <section class="news-small" id="news-small">
                    <header>
                        <h1>Department List</h>
                    </header>
                    <div class="section-content">

                        <table class="table">

                                <tbody>
                                    {% for ob in dept_list_qs %}
                                    {% if forloop.counter|divisibleby:2 %}
                                  <tr class="active">
                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                                            <a href="{% url "Academic:dept_detail"  ob.dept_name_short %}">{{ ob.dept_name }}</a>
                                        </font>
                                    </td>
                                  </tr>
                                  {% else %}
                                  <tr class="warning">
                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                                            <a href="{% url "Academic:dept_detail"  ob.dept_name_short %}">{{ ob.dept_name }}</a>
                                        </font>
                                    </td>
                                  </tr>
                                  {% endif %}
                                  {% endfor %}
                                </tbody>
                        </table>
                    </div>
                </section>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

src/templates/Academic/profile404.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <title>Profile</title>
  <style>
  .links{
      text-align: center;
  }
  </style>

</head>
<body>
{% if request.user.is_authenticated %}
<div class="container">
  <h2 style="color:red;">Error!!!</h2>
  <div class="well">
      <font face="verdana" color="red" size="5">No profile found.Please add below informations first.</font>
  </div>

  <div class="well">
      <a href="{% url "cv_portfolio:upload_resume" %}" class="btn btn-success" target="_blank">Upload Resume</a>
      <a href="{% url "cv_portfolio:create_aditionalinfo" %}" class="btn btn-success" target="_blank">Add Additional Informatione</a>
      {% if not skill_ %}
      <a href="{% url "cv_portfolio:create_skill" %}" class="btn btn-success" target="_blank">Add Skills</a>
      {% endif %}
      <a href="{% url "cv_portfolio:create_edu" %}" class="btn btn-success" target="_blank">Add Educational Informations</a>
      <a href="{% url "cv_portfolio:create_work" %}" class="btn btn-success" target="_blank">Add Work History</a>
      <a href="{% url "cv_portfolio:create_portfolio" %}" class="btn btn-success" target="_blank">Add Portfolio</a>
  </div>
</div>
{% else %}
<div class="container">
  <h2 style="color:red;">No Profile Found!!!</h2>
  <div class="well">
      <font face="verdana" color="red" size="5">User hasn't create any profile</font>
  </div>
{% endif %}
</body>
</html>

src/templates/Academic/profile_create.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Profile Create</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
{% if request.user.is_authenticated %}
<body>
    <div class="container">
        <div class-"row">
            <div class="col-xs-8 col-md-8 col-md-push-2">
                <div class="well">
                    <font face="verdana" color="green" size="10">Create Your Profile</font>
                    <form action="" method="POST">{% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" value="Create" class="btn btn-success">

                        </form>
                </div>
            </div>
        </div>
    </div>
</body>
{% else %}
<div class="container">
    <div class-"row">
        <div class="col-xs-8 col-md-8 col-md-push-2">
            <div class="well">
                <font face="verdana" color="green" size="10">Please Login</font><br>
                <a href="{% url "Users:login" %}" class="btn btn-success">Login</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
</html>

src/templates/Academic/profile_list.html
{% extends "Home/base.html" %}
{% load static %}
{% block content %}

<div class="block">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-offset-2">
                <section class="news-small" id="news-small">
                    <header>
                        <h2>Department of {{ dept_name.dept_name }}</h2>
                        <h4 style="color:blue">Academic Session {% for ob in qs %}{{ ob.academic_year }}{% endfor %}</h4>
                    </header>
                    <div class="section-content">

                        <table class="table">
                                <thead>
                                      <tr>
                                        <th>Name</th>
                                        <th>Session</th>
                                        <th>Registration</th>
                                      </tr>
                                </thead>

                                <tbody>
                                    {% for ob in qs %}
                                    {% if forloop.counter|divisibleby:2 %}

                                  <tr class="active">
                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                                            <a href="{% url "Academic:detail" ob.dept_name ob.academic_year ob.reg_number %}">{{ ob.first_name }} {{ ob.last_name }}</a>
                                        </font>
                                    </td>

                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            {{ ob.academic_year }}
                                        </font>
                                    </td>

                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            {{ ob.reg_number }}
                                        </font>
                                    </td>
                                  </tr>

                                  {% else %}

                                  <tr class="warning">
                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            <i class="fa fa-arrow-circle-right" aria-hidden="true"></i>
                                            <a href="{% url "Academic:detail" ob.dept_name ob.academic_year ob.reg_number %}">{{ ob.first_name }} {{ ob.last_name }}</a>
                                        </font>
                                    </td>


                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                        {{ ob.academic_year }}
                                        </font>
                                    </td>

                                    <td>
                                        <font face="verdana" color="green"  size="5">
                                            {{ ob.reg_number }}
                                        </font>
                                    </td>
                                  </tr>

                                  {% endif %}

                                  {% endfor %}
                                </tbody>
                        </table>

                    </div>



                <ul class="pagination">

                            {% if student_list.has_previous %}
                              <li><a href="?page={{ student_list.previous_page_number }}">&laquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&laquo;</span></li>
                            {% endif %}
                            {% for i in student_list.paginator.page_range %}
                              {% if student_list.number == i %}
                                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                              {% else %}
                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                              {% endif %}
                            {% endfor %}
                            {% if student_list.has_next %}
                              <li><a href="?page={{ student_list.next_page_number }}">&raquo;</a></li>
                            {% else %}
                              <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                </ul>

                </section>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

src/templates/Academic/profile_update.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Profile | Update</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
{% if request.user.is_authenticated %}
<body>
    <div class="container">
        <div class-"row">
            <div class="col-xs-8 col-md-8 col-md-push-2">
                <div class="well">
                    <h1 style="text-align:center;color:green;font-family:serif;">Update Profile</h1>
                    <hr style = 'background-color:#000000; border-width:0; color:#000000; height:2px; lineheight:0; display: inline-block; text-align: left; width:100%;' />
                    <form action="" method="POST">{% csrf_token %}
                            {{ form|crispy }}
                            <input type="submit" value="Update" class="btn btn-success">

                    </form>
                </div>
                <div class="col-sm-4">
                   <a href="{% url "Users:profile" %}"><span class="glyphicon glyphicon-arrow-left"></span> Back To Admin Panel</a>
                </div>
            </div>
        </div>
    </div>
</body>
{% else %}
<div class="container">
    <div class-"row">
        <div class="col-xs-8 col-md-8 col-md-push-2">
            <div class="well">
                <font face="verdana" color="green" size="10">Please Login</font><br>
                <a href="{% url "Users:login" %}" class="btn btn-success">Login</a>
            </div>
        </div>
    </div>
</div>
{% endif %}
</html>