src/Academic/urls.py
from django.conf.urls import url
from . import views
from cv_portfolio.views import PreviewCV,PortfolioView

app_name="Academic"

urlpatterns = [
    url(r'^$', views.DepartmentView,name="dept_list"),
    url(r'^(?P<dept_name_short>[-\w]+)/list/$', views.DepartmentDetail,name="dept_detail"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/$', views.StudentList,name="profile_list"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/$', views.StudentDetail,name="detail"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/edit/$', views.ProfileUpdate,name="update"),
    url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/cv/$',PreviewCV,name="cv"),
    # url(r'^(?P<dept_name>[-\w]+)/list/(?P<dept_session>[\w-]+)/(?P<reg_number>[\w-]+)/portfolio/$',PortfolioView,name="portfolio"),
    url(r'^profile/create/$', views.ProfileCreate,name="create"),


]

src/Campus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^$',views.Home,name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^department/',include("Academic.urls")),
    url(r'^students/',include("Users.urls")),
    url(r'^',include("cv_portfolio.urls")),
    url(r'^',include("Notifications.urls")),
    url(r'^', include('django.contrib.auth.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/Users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name="Users"

urlpatterns = [

    url(r'^register/$',views.Register,name="register"),
    url(r'^login/$',views.UserLogin,name="login"),
    url(r'^logout/$',views.User_Logout,name="logout"),
    url(r'^profile/$',views.ProfileView,name="profile"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',views.ActivateProfile,name="activate"),

    # Password Reset

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views. password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # Password Change

    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),

]

src/Users/models.py
import datetime
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import (
    BaseUserManager, AbstractBaseUser
)
from django.conf import settings
from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from .utils import Key_Generator
from django.core.mail import send_mail
from Academic.models import Department
from Academic.utils import year_dropdown


USERNAME_REGEX="^[a-zA-Z0-9.+_-]*$"



class MyUserManager(BaseUserManager):

    def create_user(self, username,email, password=None):

        """
        Creates and saves a User with the given username, email and password.
        """

        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(

            username    =username,
            email       =self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,username,email, password):

        """
        Creates and saves a User with the given username, email and password.
        """

        user            = self.create_user(

                            username,
                            email,
                            password=password,
                        )

        user.is_admin   = True
        user.is_staff   =True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):

    username        =models.CharField(

                        max_length=250,
                        validators=[
                                RegexValidator(

                                    regex   =USERNAME_REGEX,
                                    message ='Username must be Alphanumeric or contain any of this ". + _ - "',
                                    code    ='Invalid Username '
                        )],
                        unique=True
                    )

    email              = models.EmailField(
                        verbose_name='email address',
                        max_length=255,
                        unique=True,
                        )

    is_active       = models.BooleanField(default=True)
    is_staff        = models.BooleanField(default=False)
    is_admin        = models.BooleanField(default=False)

    objects         = MyUserManager()

    USERNAME_FIELD  = 'username'
    REQUIRED_FIELDS = ['email']

    def get_full_name(self):

        return self.email

    def get_short_name(self):

        return self.email

    def __str__(self):          # __unicode__ on Python 2

        return self.username

    def has_perm(self, perm, obj=None):


        return True

    def has_module_perms(self, app_label):

        return True



class ActivationProfile(models.Model):

    user        =models.ForeignKey(settings.AUTH_USER_MODEL)
    key         =models.CharField(max_length=120)
    expired     =models.BooleanField(default=False)

    def save(self,*args,**kwargs):
        self.key=Key_Generator()
        super(ActivationProfile,self).save(*args,**kwargs)

        subject = 'Activate Account'
        from_email = settings.DEFAULT_FROM_EMAIL
        message = "http://127.0.0.1:8000/students/activate/"+self.key
        recipient_list = [self.user.email]

        sent_mail=send_mail(
                            subject,
                            message,
                            from_email,
                            recipient_list,
                            fail_silently=False,
                            )
        return sent_mail

    def __str__(self):

        return str(self.user.username)

    class Meta:

        ordering=["user"]



class Profile(models.Model):

    user                =models.OneToOneField(settings.AUTH_USER_MODEL)
    first_name          =models.CharField(max_length=250,default="")
    last_name           =models.CharField(max_length=250,default="")
    fathers_name        =models.CharField(max_length=250,default="")
    mothers_name        =models.CharField(max_length=250,default="")
    dept_name           =models.ForeignKey(Department,on_delete=models.CASCADE,default="")
    reg_number          =models.CharField(max_length=120,default="")
    academic_year       =models.IntegerField(('Academic Year'),choices=year_dropdown,default=datetime.datetime.now().year)
    CGPA                =models.CharField(max_length=250,default="")

    class Meta:

        ordering=["reg_number"]

    def __str__(self):

        return str(self.user.username)

    def get_absolute_url(self):

        return reverse("Academic:detail",kwargs={"dept_name":self.dept_name,"dept_session":self.academic_year,"reg_number":self.reg_number})

def post_save_user_model_receiver(sender,instance,created,*args,**kwargs):

    if created:

        try:
            ActivationProfile.objects.create(user=instance)
        except:
            pass

post_save.connect(post_save_user_model_receiver,sender=settings.AUTH_USER_MODEL)

src/Users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.auth import get_user_model
from .models import USERNAME_REGEX
from django.core.validators import RegexValidator
from django.db.models import Q
from .models import Profile



User=get_user_model()



class UserLoginForm(forms.Form):

    query        =forms.CharField(label='Username/Email')
    password     = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self,*args,**kwargs):

        query       =self.cleaned_data.get('query')
        password    =self.cleaned_data.get('password')

        user_qs=User.objects.filter(

                                Q(username__iexact=query)|
                                Q(email__iexact=query)
                            ).distinct()

        if not user_qs.exists() and user_qs.count() != 1:
            raise forms.ValidationError("Invalid credentials --Username/Email not exists")

        user_obj    =user_qs.first()

        if not user_obj.check_password(password):

            raise forms.ValidationError("Invalid credentials --Invalid Password")

        if not user_obj.is_active:

            raise forms.ValidationError("Inactive User.Please verify your email.")

        self.cleaned_data["user_obj"]=user_obj

        return super(UserLoginForm,self).clean(*args,**kwargs)


class UserCreationForm(forms.ModelForm):


    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','email',)

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):

        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.is_active=False
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('username','email', 'password', 'is_staff', 'is_active', 'is_admin')

    def clean_password(self):

        return self.initial["password"]

class ProfileUpdateForm(forms.ModelForm):

    class Meta:

        model = Profile
        fields = (
        'first_name',
        'last_name',
        'fathers_name',
        'mothers_name',
        'dept_name',
        'reg_number',
        'academic_year',
        'CGPA',
        )

class ProfileCreateForm(forms.ModelForm):

    class Meta:

        model=Profile

        fields = (
        'first_name',
        'last_name',
        'fathers_name',
        'mothers_name',
        'dept_name',
        'reg_number',
        'academic_year',
        'CGPA',
        )

src/Users/views.py
from datetime import date
from django.shortcuts import render
from django.contrib import messages
from .forms import UserCreationForm,UserLoginForm
from django.contrib.auth import login,get_user_model,logout
from django.http import HttpResponseRedirect,Http404
from .models import ActivationProfile,Profile
from Notifications.models import AdminMessage
from cv_portfolio.models import TechnicalSkills,WorkHistory,Portfolio,Service


User=get_user_model()



def Register(request,*args,**kwargs):

    form=UserCreationForm(request.POST or None)

    if form.is_valid():
        form.save()
        messages.success(request,"Successfully registered.Please Check your email to activate your Account")
        return HttpResponseRedirect("/students/login")

    template_name="Users/register.html"
    context={
                "form":form

            }

    return render(request,template_name,context)


def UserLogin(request,*args,**kwargs):

    form=UserLoginForm(request.POST or None)

    if form.is_valid():

        user_obj =form.cleaned_data.get('user_obj')
        login(request,user_obj)
        return HttpResponseRedirect("/students/profile")

    template_name="Users/login.html"
    context={
                "form":form

            }
    return render(request,template_name,context)


def User_Logout(request):

    logout(request)
    messages.success(request,"Successfully Logged out.")
    return HttpResponseRedirect("/students/login")

# Activate Profile.Need to activate profile for login.

def ActivateProfile(request,code=None,*args,**kwars):

    if code:

        act_profile_qs=ActivationProfile.objects.filter(key=code)

        if act_profile_qs.exists() and act_profile_qs.count() == 1:

            act_obj=act_profile_qs.first()
            if not act_obj.expired:

                user_obj=act_obj.user
                user_obj.is_active=True
                user_obj.save()
                act_obj.expired=True
                act_obj.save()
                messages.success(request,"Successfully activated your accounts.Now you can login to our site")
                return HttpResponseRedirect("/students/login")

    raise Http404

# User Admin Panel.

def ProfileView(request):

    try:

        if request.user.is_authenticated:


            qs=Profile.objects.get(user=request.user)
            skill_=TechnicalSkills.objects.filter(user=qs.user)
            work_history=WorkHistory.objects.filter(user=qs.user).count()
            port_folio=Portfolio.objects.filter(user=qs.user).count()
            total_skill=skill_.count()
            today = date.today()
            notifications=AdminMessage.objects.filter(publish__year=today.year, publish__month=today.month, publish__day=today.day)
            message_=AdminMessage.objects.all()[:10]
            service_info=Service.objects.filter(user=qs.user).count()
            template_name="Users/profile.html"
            context={
                        "qs":qs,
                        "total_skill":total_skill,
                        "work_history":work_history,
                        "port_folio":port_folio,
                        "notifications":notifications,
                        "message_":message_,
                        "service_info":service_info
                    }

            return render(request,template_name,context)
        else:
            return HttpResponseRedirect("/students/login")

    except:

        return render(request,"Users/profile404.html",{})

src/templates/Users/form.html
<form method="POST" action="">  {% csrf_token %} 

{{ form.as_p }}

<input type="submit" value="Submit"/>

</form>

src/templates/Users/login.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Login | Admin Site</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<style>

    .main{
       height: auto;  /* footer height */
       padding-top: 20px;
       display: block;
       margin-top: 10%; /* space between content and footer */
       box-sizing: border-box;
       position: relative;
       width: auto;
    }
</style>
</head>
<body>
<section class="main">
            <div class="container">
                <div class-"row">
                    <div class="col-xs-6 col-md-6 col-md-push-3">
                        <div class="well">
                            <font face="verdana" color="green" size="10">Administrator Login</font>

                            {% if messages %}
                                <div class='messages'>

                                <ul class="messages">
                                {% for message in messages %}
                                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
                                {% endfor %}
                                </ul>

                                </div>
                            {% endif %}


                            <form action="" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                                    {{ form|crispy }}
                                    <input type="submit" value="Login" class="btn btn-success">
                            </form>
                            <br>
                            <h4 style="text-align:center">Don't have account ? You can register from <a href="{% url "Users:register" %}">here.</a><h4>
                            <br>

                            <h4 style="text-align:center">Forgot Password ? You can reset password from <a href="{% url "Users:password_reset" %}">here.</a><h4>
                            <br>

                            <div style="text-align:center">
                            <a href="{% url "home" %}" class="btn btn-primary">Back To Home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </body>
</body>
</html>

src/templates/Users/profile404.html
{% load static %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <title>Profile</title>
  <style>
  .links{
      text-align: center;
  }
  </style>

</head>
<body>

<div class="container">
  <h2 style="color:red;">Error!!!</h2>
  <div class="well">
      <font face="verdana" color="red" size="5">No profile found.Please create your profile first.</font>
  </div>

  <div class="links">
      <a href="{% url "Academic:create" %}" class="btn btn-success">Create Your Profile</a>
  </div>
</div>

</body>
</html>

src/templates/Users/profile_not_found.html
<h1>You don't create your profile.</h1><br>
<a href="{% url "Academic:create" %}">Create Profile</a>

src/templates/Users/register.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Register</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<style>

    .main{
       height: auto;  /* footer height */
       padding-top: 20px;
       display: block;
       margin-top: 4%; /* space between content and footer */
       box-sizing: border-box;
       position: relative;
       width: auto;
    }
</style>
</head>
<body>
<section class="main">
            <div class="container">
                <div class-"row">
                    <div class="col-xs-8 col-md-8 col-md-push-2">
                        <div class="well">
                            <font face="verdana" color="green" size="10">Register To This Site</font>

                            <form action="" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                                    {{ form|crispy }}
                                    <input type="submit" value="Register" class="btn btn-success">
                            </form>
                            <br>
                            <h4 style="text-align:center;">Already have account ? Then you can login from <a href="{% url "Users:login" %}">here.</a></h4>
                            <br>
                            <div style="text-align:center">
                            <a href="{% url "home" %}" class="btn btn-primary">Back To Home</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </body>
</body>
</html>

src/templates/Users/registration_confirm.html
You registration is pending.To activate your account please check your email

<br>
<a href="{% url "Users:register" %}">Registration Page</a>