src/Campus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [

    url(r'^$',views.Home,name="home"),
    url(r'^admin/', admin.site.urls),
    url(r'^department/',include("Academic.urls")),
    url(r'^students/',include("Users.urls")),
    url(r'^',include("cv_portfolio.urls")),
    url(r'^',include("Notifications.urls")),
    url(r'^', include('django.contrib.auth.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/Users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name="Users"

urlpatterns = [

    url(r'^register/$',views.Register,name="register"),
    url(r'^login/$',views.UserLogin,name="login"),
    url(r'^logout/$',views.User_Logout,name="logout"),
    url(r'^profile/$',views.ProfileView,name="profile"),
    url(r'^activate/(?P<code>[a-z0-9].*)/$',views.ActivateProfile,name="activate"),

    # Password Reset

    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views. password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),

    # Password Change

    url(r'^password_change/$', auth_views.password_change, name='password_change'),
    url(r'^password_change/done/$', auth_views.password_change_done, name='password_change_done'),

]

src/cv_portfolio/urls.py
from django.conf.urls import url
from . import views

app_name="cv_portfolio"

urlpatterns = [

    # Create Informations

    url(r'^aditionalinfo/create/$', views.CreateAdditionalInfo,name="create_aditionalinfo"),
    url(r'^resume/upload/$', views.UploadResume,name="upload_resume"),
    url(r'^portfolio/create/$', views.PortfolioView,name="create_portfolio"),
    url(r'^skills/create/$', views.CreateTechnicalSkill,name="create_skill"),
    url(r'^education/create/$', views.CreateEducationalInfo,name="create_edu"),
    url(r'^work/create/$', views.CreateWorkHistory,name="create_work"),
    url(r'^service/create/$', views.ServiceCreationView,name="service"),
    url(r'^success/create/$', views.CreationSuccessInfo,name="success"),
    url(r'^working_process/create/$', views.CreationWorkingProcess,name="working_process"),
    url(r'^clients/create/$', views.CreateClients,name="create_clients"),

    # List and Detail

    url(r'^skills/list/$', views.SkillList,name="skill_list"),
    url(r'^(?P<user>[-\w]+)/skills/(?P<pk>[-\d]+)/detail/$', views.Skilldetail,name="skill_detail"),

    url(r'^portfolio/list/$', views.PortfolioList,name="portfolio_list"),
    url(r'^portfolio/(?P<pk>[-\d]+)/detail/$', views.PortfolioDetail,name="portfolio_detail"),
    url(r'^(?P<user>[-\w]+)/portfolio/(?P<pk>[-\d]+)/detail/$', views.PortfolioDetailforUser,name="portfolio_detail_user"),

    url(r'^education/list/$', views.EducationalInfoList,name="edu_list"),
    url(r'^(?P<user>[-\w]+)/education/(?P<pk>[-\d]+)/detail/$', views.EducationalInfoDetail,name="edu_detail"),

    url(r'^work/list/$', views.WorkHistoryList,name="work_list"),
    url(r'^(?P<user>[-\w]+)/work/(?P<pk>[-\d]+)/detail/$', views.DetailHistoryList,name="work_detail"),

    url(r'^service/list/$', views.ServiceInfoList,name="service_list"),
    url(r'^(?P<user>[-\w]+)/service/(?P<pk>[-\d]+)/detail/$', views.ServiceInfoDetail,name="service_detail"),

    url(r'^working_process/list/$', views.WorkingProcessList,name="working_process_list"),
    url(r'^(?P<user>[-\w]+)/working_process/(?P<pk>[-\d]+)/detail/$', views.WorkingProcessDetail,name="working_process_detail"),

    url(r'^clients/list/$', views.ClientList,name="clients_list"),
    url(r'^(?P<user>[-\w]+)/clients/(?P<pk>[-\d]+)/detail/$', views.ClientDetail,name="clients_detail"),




    # Update Informations

    url(r'^aditionalinfo/edit/$', views.UpdateAdditionalInfo,name="update_aditionalinfo"),
    url(r'^resume/edit/$', views.UpdateResume,name="update_resume"),
    url(r'^success/edit/$', views.UpdateSuccessInfo,name="update_success"),
    url(r'^(?P<user>[-\w]+)/skills/(?P<pk>[-\d]+)/edit/$', views.UpdateTechnicalSkill,name="update_skill"),
    url(r'^(?P<user>[-\w]+)/education/(?P<pk>[-\d]+)/edit/$', views.UpdateEducationalInfo,name="update_edu"),
    url(r'^(?P<user>[-\w]+)/portfolio/(?P<pk>[-\d]+)/edit/$', views.UpdatePortfolio,name="update_portfolio"),
    url(r'^(?P<user>[-\w]+)/work/(?P<pk>[-\d]+)/edit/$', views.UpdateWorkHistory,name="update_work"),
    url(r'^(?P<user>[-\w]+)/service/(?P<pk>[-\d]+)/edit/$', views.UpdateServiceInfo,name="update_service_info"),
    url(r'^(?P<user>[-\w]+)/working_process/(?P<pk>[-\d]+)/edit/$', views.UpdateWorkingProcess,name="update_working_process"),
    url(r'^(?P<user>[-\w]+)/clients/(?P<pk>[-\d]+)/edit/$', views.UpdateClients,name="update_clients"),


    # Delete Informations

    url(r'^(?P<user>[-\w]+)/skills/(?P<pk>[-\d]+)/delete/$', views.DeleteTechnicalSkill,name="delete_skill"),
    url(r'^(?P<user>[-\w]+)/education/(?P<pk>[-\d]+)/delete/$', views.DeleteEducationalInfo,name="delete_edu"),
    url(r'^(?P<user>[-\w]+)/portfolio/(?P<pk>[-\d]+)/delete/$', views.DeletePortfolio,name="delete_portfolio"),
    url(r'^(?P<user>[-\w]+)/work/(?P<pk>[-\d]+)/delete/$', views.DeleteWorkHistory,name="delete_work"),
    url(r'^(?P<user>[-\w]+)/service/(?P<pk>[-\d]+)/delete/$', views.DeleteService,name="delete_service"),
    url(r'^(?P<user>[-\w]+)/working_process/(?P<pk>[-\d]+)/delete/$', views.DeleteWorkingProcess,name="delete_working_process"),
    url(r'^(?P<user>[-\w]+)/clients/(?P<pk>[-\d]+)/delete/$', views.DeleteClients,name="delete_clients"),



]

src/cv_portfolio/forms.py
from django import forms
from .models import (
                AdditionalInfo,
                UploadCV,
                Portfolio,
                TechnicalSkills,
                Education,
                WorkHistory,
                Service,
                Succeess,
                WorkingProcess,
                Clients
                )


class AdditinalInfoCreationForm(forms.ModelForm):

    class Meta:

        model=AdditionalInfo
        exclude = ['user']

class ResumeUploadForm(forms.ModelForm):

    class Meta:

        model=UploadCV
        exclude = ['user']


class PortfolioForm(forms.ModelForm):

    class Meta:

        model=Portfolio
        exclude = ['user']

class TechnicalSkillCreateForm(forms.ModelForm):

    class Meta:

        model=TechnicalSkills
        exclude = ['user']


class EducationalInfoForm(forms.ModelForm):

    class Meta:

        model=Education
        exclude = ['user']


class WorkHistoryForm(forms.ModelForm):

    class Meta:

        model=WorkHistory
        exclude = ['user']


class ServiceCreationForm(forms.ModelForm):

    class Meta:

        model=Service
        exclude = ['user']


class SuccessCreationForm(forms.ModelForm):

    class Meta:

        model=Succeess
        exclude = ['user']


class WorkingProcessCreationForm(forms.ModelForm):

    class Meta:

        model=WorkingProcess
        exclude = ['user']

class ClientsCreationForm(forms.ModelForm):

    class Meta:

        model=Clients
        exclude = ['user']

src/cv_portfolio/views.py
from django.shortcuts import render
from django.contrib import messages
from django.http import HttpResponseRedirect,HttpResponse,Http404
from Academic.models import Department
from Users.models import Profile
from .models import (
                    UploadCV,
                    AdditionalInfo,
                    Portfolio,
                    TechnicalSkills,
                    Education,
                    WorkHistory,
                    Service,
                    Succeess,
                    WorkingProcess,
                    Clients
                    )

from .forms import (
                    AdditinalInfoCreationForm,
                    ResumeUploadForm,
                    PortfolioForm,
                    TechnicalSkillCreateForm,
                    EducationalInfoForm,
                    WorkHistoryForm,
                    ServiceCreationForm,
                    SuccessCreationForm,
                    WorkingProcessCreationForm,
                    ClientsCreationForm
                    )



def PreviewCV(request,dept_name=None,dept_session=None,reg_number=None):

    dept_name   =Department.objects.get(dept_name_short=dept_name)

    try:
        if dept_name:

            qs=Profile.objects.get(dept_name=dept_name,academic_year=dept_session,reg_number=reg_number)
            cv=UploadCV.objects.get(user=qs.user)

        template_name="cv_portfolio/cv.html"
        context={"cv":cv,"qs":qs}

        return render(request,template_name,context)
    except:
        return render(request,"cv_portfolio/cv_not_found.html")

# Create Additional Information

def CreateAdditionalInfo(request):

    user_exists=AdditionalInfo.objects.filter(user=request.user).exists()
    form=AdditinalInfoCreationForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        if not user_exists:
            instance.save()
            messages.success(request, "Successfully Added Additional Informations")
            return HttpResponseRedirect("/students/profile")
        else:
            return render(request,"cv_portfolio/exists.html",{})

    template_name="cv_portfolio/create_additional_info.html"
    context={"form":form}

    return render(request,template_name,context)

# Update Additional Informations

def UpdateAdditionalInfo(request):

    instance=AdditionalInfo.objects.get(user=request.user)
    form=AdditinalInfoCreationForm(request.POST or None, request.FILES or None,instance=instance)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Updated Additional Informations")
        return HttpResponseRedirect("/students/profile")

    template_name="cv_portfolio/update_additional_info.html"
    context={"form":form}

    return render(request,template_name,context)

# Create Skills

def CreateTechnicalSkill(request):

    form=TechnicalSkillCreateForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Created Technical Skills")
        return HttpResponseRedirect("/students/profile")

    template_name="cv_portfolio/create_skill.html"
    context={"form":form}

    return render(request,template_name,context)

# Skill Lists

def SkillList(request):

    qs=TechnicalSkills.objects.filter(user=request.user)
    template_name="cv_portfolio/skill_list.html"
    context={"qs":qs}

    return render(request,template_name,context)

# Skills Detail

def Skilldetail(request,user=None,pk=None):

    qs=TechnicalSkills.objects.get(user=request.user,pk=pk)
    template_name="cv_portfolio/skill_detail.html"
    context={"qs":qs}

    return render(request,template_name,context)

# Update Skills

def UpdateTechnicalSkill(request,user=None,pk=None):

    instance=TechnicalSkills.objects.get(user=request.user,pk=pk)
    form=TechnicalSkillCreateForm(request.POST or None, request.FILES or None,instance=instance)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Updated Technical Skills")
        return HttpResponseRedirect("/students/profile")

    template_name="cv_portfolio/update_skill.html"
    context={"form":form,"instance":instance}

    return render(request,template_name,context)

# Delete Skills

def DeleteTechnicalSkill(request,user=None,pk=None):

    if not request.user.is_authenticated:
        raise Http404

    instance=TechnicalSkills.objects.get(user=request.user,pk=pk)
    instance.delete()
    messages.success(request, "Successfully Deleted Technical Skills")
    return HttpResponseRedirect("/students/profile")

# Create Educational Informations

def CreateEducationalInfo(request):

    form=EducationalInfoForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Added Educational Informations")
        return HttpResponseRedirect("/students/profile")

    template_name="cv_portfolio/create_edu.html"
    context={"form":form}

    return render(request,template_name,context)

# Educational Informations List

def EducationalInfoList(request):

    qs=Education.objects.filter(user=request.user)
    template_name="cv_portfolio/edu_info_list.html"
    context={"qs":qs}

    return render(request,template_name,context)

# Educational Informations Detail

def EducationalInfoDetail(request,user=None,pk=None):

    qs=Education.objects.get(user=request.user,pk=pk)
    template_name="cv_portfolio/edu_info_detail.html"
    context={"qs":qs}

    return render(request,template_name,context)

# Update Educational Informations

def UpdateEducationalInfo(request,user=None,pk=None):

    instance=Education.objects.get(user=request.user,pk=pk)
    form=EducationalInfoForm(request.POST or None, request.FILES or None,instance=instance)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Updated Educational Informations")
        return HttpResponseRedirect("/students/profile")

    template_name="cv_portfolio/update_edu.html"
    context={"form":form,"instance":instance}

    return render(request,template_name,context)

# Delete Educational Informations

def DeleteEducationalInfo(request,user=None,pk=None):

    if not request.user.is_authenticated:
        raise Http404

    instance=Education.objects.get(user=request.user,pk=pk)
    instance.delete()
    messages.success(request, "Successfully Deleted Educational Informations")
    return HttpResponseRedirect("/students/profile")

# Create Work History

def CreateWorkHistory(request):

    form=WorkHistoryForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Added Work History")
        return HttpResponseRedirect("/students/profile")

    template_name="cv_portfolio/create_work.html"
    context={"form":form}

    return render(request,template_name,context)

# Work History Detail

def WorkHistoryList(request):

    qs=WorkHistory.objects.filter(user=request.user)
    template_name="cv_portfolio/list_work.html"
    context={"qs":qs}

    return render(request,template_name,context)

# Detail Work History

def DetailHistoryList(request,user=None,pk=None):

    qs=WorkHistory.objects.get(user=request.user,pk=pk)
    template_name="cv_portfolio/detail_work.html"
    context={"qs":qs}

    return render(request,template_name,context)

# Update Work Hiwstory

def UpdateWorkHistory(request,user=None,pk=None):

    instance=WorkHistory.objects.get(user=request.user,pk=pk)
    form=WorkHistoryForm(request.POST or None, request.FILES or None,instance=instance)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()
        messages.success(request, "Successfully Updated Work History")
        return HttpResponseRedirect("/students/profile")

    template_name="cv_portfolio/update_work.html"
    context={"form":form,"instance":instance}

    return render(request,template_name,context)

# Delete Work History

def DeleteWorkHistory(request,user=None,pk=None):

    if not request.user.is_authenticated:
        raise Http404

    instance=WorkHistory.objects.get(user=request.user,pk=pk)
    instance.delete()
    messages.success(request, "Successfully Deleted Work History")
    return HttpResponseRedirect("/students/profile")


# Upload Resume

def UploadResume(request):

    user_exists=UploadCV.objects.filter(user=request.user).exists()
    form=ResumeUploadForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        if not user_exists:
            instance.save()
            messages.success(request, "Successfully Upload Your Resume")
            return HttpResponseRedirect("/students/profile")
        else:
            return render(request,"cv_portfolio/exists.html",{})

    template_name="cv_portfolio/upload_resume.html"
    context={"form":form}

    return render(request,template_name,context)

# Update Resume

def UpdateResume(request):

    instance=UploadCV.objects.get(user=request.user)
    form=ResumeUploadForm(request.POST or None, request.FILES or None,instance=instance)

    if form.is_valid():
        instance=form.save(commit=False)
        instance.user=request.user
        instance.save()

src/templates/cv_portfolio/create_additional_info.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Profile | Additional Informations</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<style>

    .main{
       height: auto;  /* footer height */
       padding-top: 20px;
       display: block;
       margin-bottom: 1%;
       box-sizing: border-box;
       position: relative;
       width: auto;
    }
</style>

</head>
{% if request.user.is_authenticated %}
<body>
<section class="main">
            <div class="container">
                <div class-"row">
                    <div class="col-xs-12 col-md-12">
                        <div class="well">
                            <h1 style="text-align:center;color:green;font-family:serif;">Create Additional Informations</h1>
                            <hr style = 'background-color:#000000; border-width:0; color:#000000; height:2px; lineheight:0; display: inline-block; text-align: left; width:100%;' />
                            <form action="" method="POST" enctype='multipart/form-data'>{% csrf_token %}
                                    {{ form|crispy }}
                                    <input type="submit" value="Create" class="btn btn-success">
                            </form>
                        </div>

                        <div class="col-sm-4">
                            <a href="{% url "Users:profile" %}"><span class="glyphicon glyphicon-arrow-left"></span> Back To Admin Panel</a>
                        </div>
                    </div>
                </div>
            </div>
        </body>
        {% else %}
        <div class="container">
            <div class-"row">
                <div class="col-xs-8 col-md-8 col-md-push-2">
                    <div class="well">
                        <font face="verdana" color="green" size="10">Please Login</font><br>
                        <a href="{% url "Users:login" %}" class="btn btn-success">Login</a>
                    </div>
                </div>
            </div>
            </div>
</section>
{% endif %}
</body>
</html>

src/templates/cv_portfolio/detail_work.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Work | Detail</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>

    .main{
       height: auto;  /* footer height */
       padding-top: 20px;
       display: block;
       margin-top: 10%; /* space between content and footer */
       box-sizing: border-box;
       position: relative;
       width: auto;
    }
</style>

</head>
{% if request.user.is_authenticated %}
<body>
<section class="main">
            <div class="container">
                <div class-"row">
                    <div class="col-xs-9 col-md-9 col-md-push-2">
                        <div class="well">
                            <h1 style="text-align:center;color:green;font-family:serif;">Work History</h1>
                            <hr style = 'background-color:#000000; border-width:0; color:#000000; height:2px; lineheight:0; display: inline-block; text-align: left; width:100%;' />
                            <font face="verdana" color="black" size="3">Name of Company :</font>
                            <font face="verdana" color="green" size="5">{{ qs.company_name }}</font><br>
                            <font face="verdana" color="black" size="3">Position :</font>
                            <font face="verdana" color="green" size="5">{{ qs.position }}</font><br>
                            <font face="verdana" color="black" size="3">Duration :</font>
                            <font face="verdana" color="blue" size="5">{{ qs.start_date }} to {{ qs.end_date }}</font>
                        </div>
                        <div class="col-sm-4 col-sm-push-4">
                            <a href="{% url "cv_portfolio:work_list" %}" class="btn btn-block  btn-primary">Back</a>
                            <br>
                            <a href="{% url "cv_portfolio:update_work" qs.user qs.pk %}" class="btn btn-block  btn-success">Update</a>
                            <br>
                            <a href="{% url "cv_portfolio:delete_work" qs.user qs.pk %}" class="btn btn-block  btn-danger">Delete</a>
                        </div>

                    </div>
                </div>
            </div>
        </body>
        {% else %}
        <div class="container">
            <div class-"row">
                <div class="col-xs-8 col-md-8 col-md-push-2">
                    <div class="well">
                        <font face="verdana" color="green" size="10">Please Login</font><br>
                        <a href="{% url "Users:login" %}" class="btn btn-success">Login</a>
                    </div>
                </div>
            </div>
            </div>
</section>
{% endif %}
</body>
</html>

src/templates/cv_portfolio/portfolio.html
{% load static %}
<h1>Portfolio of {{ qs.first_name}} {{ qs.last_name }}</h1>

Name of Project : {{ port_folio.project_name }}

src/templates/cv_portfolio/portfolio_detail_user.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Education | Detail</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>

    .main{
       height: auto;  /* footer height */
       padding-top: 20px;
       display: block;
       margin-bottom: 1%; /* space between content and footer */
       box-sizing: border-box;
       position: relative;
       width: auto;
    }
</style>

</head>
{% if request.user.is_authenticated %}
<body>
<section class="main">
            <div class="container">
                <div class-"row">
                    <div class="col-xs-9 col-md-9 col-md-push-2">
                        <div class="well">

                            <h1 style="text-align:center;color:green;font-family:serif;">Portfolio Detail</h1>
                            <hr style = 'background-color:#000000; border-width:0; color:#000000; height:2px; lineheight:0; display: inline-block; text-align: left; width:100%;' />
                            <img src="{{ qs.project_image.url }}" class="img-responsive"><br>
                            <font face="verdana" color="black" size="3">Name of Project :</font>
                            <font face="verdana" color="green" size="5">{{ qs.project_name }}</font><br>
                            <font face="verdana" color="black" size="3">Project Type :</font>
                            <font face="verdana" color="green" size="5">{{ qs.project_type }}</font><br>
                            <font face="verdana" color="black" size="3">Client :</font>
                            <font face="verdana" color="green" size="5">{{ qs.clients }}</font><br>
                            <font face="verdana" color="black" size="3">Project URL :</font>
                            <font face="verdana" color="green" size="5"><a href="{{ qs.project_url }}" target="_blank">{{ qs.project_url }}</a></font>

                        </div>
                        <div class="col-sm-4 col-sm-push-4">
                            <a href="{% url "cv_portfolio:portfolio_list" %}" class="btn btn-block btn-primary ">Back</a>
                            <br>
                            <a href="{% url "cv_portfolio:update_portfolio" qs.user qs.pk %}" class="btn btn-block  btn-success">Update</a>
                            <br>
                            <a href="{% url "cv_portfolio:delete_portfolio" qs.user qs.pk %}" class="btn btn-block  btn-danger">Delete</a>
                        </div>

                    </div>
                </div>
            </div>
        </body>
        {% else %}
        <div class="container">
            <div class-"row">
                <div class="col-xs-8 col-md-8 col-md-push-2">
                    <div class="well">
                        <font face="verdana" color="green" size="10">Please Login</font><br>
                        <a href="{% url "Users:login" %}" class="btn btn-success">Login</a>
                    </div>
                </div>
            </div>
            </div>
</section>
{% endif %}
</body>
</html>